### PR TITLE
Create index.html

### PR DESCRIPTION
**Pull request by Tejas9019**

### CODE REVIEW

**Review by msramesh2k1 — CHANGES_REQUESTED** [review]
Try to give valid Pull Request which contains all files

**Comment by msramesh2k1** [comment]
msramesh2k1@gmail.com mail me asap

**Comment by Tejas9019** [comment]
> Try to give valid Pull Request which contains all files

Sir it is not taking

**Comment by msramesh2k1** [comment]
tell your mail id

**Comment by Tejas9019** [comment]
> tell your mail id

tejasd603@gmail.com

**Pull request closed without merging**
