### PR TITLE
Gayathri Devi Nagalapuram - DevHack22

### PR DESCRIPTION
**Pull request by gayathri1462**
Hello, 

I am Gayathri Devi Nagalpuram submitting my code and demo for problem statement of Machine Learning Domain.

Thank you.

### CODE REVIEW

**Review by msramesh2k1 — CHANGES_REQUESTED** [review]
Thanks for the participation , 
You have to make two changes 
- Add dataset inside your folder
- add description of your project in Readme

**Comment by gayathri1462** [comment]
I have made the changes mentioned. Please let me know if any changes need to be made. Thank you.

**Review by msramesh2k1 — APPROVED** [review]
great work !!!

**Comment by gayathri1462** [comment]
Thanks a lot!

**Pull request merged**
