### PR TITLE
snega-s

### PR DESCRIPTION
**Pull request by snega16**
Machine Learning - Glass Prediction
By SNEGA S

### CODE REVIEW

**Review by msramesh2k1 — CHANGES_REQUESTED** [review]
Thanks for the participation !!!

You have to make few changes 

- Make description of your project and insert a link of your video in readme file not in any other file 
- try to upload dataset as well

**Comment by snega16** [comment]
> Thanks for the participation !!!
> 
> You have to make few changes
> 
> * Make description of your project and insert a link of your video in readme file not in any other file
> * try to upload dataset as well

Changes Made.

**Comment by snega16** [comment]
> Thanks for the participation !!!
> 
> You have to make few changes
> 
> * Make description of your project and insert a link of your video in readme file not in any other file
> * try to upload dataset as well

Changes made!

**Review by msramesh2k1 — APPROVED** [review]
Thanks for the update , will announce the result soon .

**Pull request merged**
